I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/core/locations/location_init.rpy", line 1, in script
    init -2 python:
  File "game/core/locations/location_init.rpy", line 3, in <module>
    L_home_bedroom = Location("Bedroom", background_key="home_bedroom", parents=[None], label="player_bedroom", ref="bedroom_screen")
NameError: name 'Location' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/core/locations/location_init.rpy", line 1, in script
    init -2 python:
  File "C:\Program Files\renpy-8.2.1-sdk\renpy-8.2.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files\renpy-8.2.1-sdk\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/core/locations/location_init.rpy", line 3, in <module>
    L_home_bedroom = Location("Bedroom", background_key="home_bedroom", parents=[None], label="player_bedroom", ref="bedroom_screen")
NameError: name 'Location' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.2.3.24061702
YoutubeVNGame 1.0
Mon Dec 23 15:58:52 2024
